"use client";

import React, { useState, useMemo } from "react";
import {
    FileText,
    ListChecks,
    ClipboardList,
    CheckCircle2,
    Loader2,
    Calendar,
    Users,
    Clock,
    Sparkles,
    AlertCircle,
    User,
} from "lucide-react";
import type { ExecutionComponentProps } from "../../types";

// Types for parsed data
interface ActionItem {
    task: string;
    owner: string;
    deadline: string;
}

interface MeetingDetails {
    title: string;
    date: string;
    duration: string;
    attendees: string[];
    agenda: string;
}

interface ParsedMeetingData {
    meetingDetails: MeetingDetails | null;
    summary: string;
    summaryHtml: string;
    mom: string;
    momHtml: string;
    actionItems: ActionItem[];
    actionItemsHtml: string;
    emailSent: boolean;
    emailId: string;
    trackingId: string;
}

// Helper functions (defined outside component to avoid hoisting issues)

// Helper: Strip HTML tags
const stripHtml = (html: string): string => {
    return html.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
};

// Helper: Extract meeting details from MOM HTML
const extractMeetingDetails = (html: string): MeetingDetails | null => {
    try {
        const titleMatch = html.match(/Meeting Title:<\/strong>\s*([^<]+)/);
        const dateMatch = html.match(/Date \/ Time:<\/strong>\s*([^<]+)/);
        const attendeesMatch = html.match(/Attendees:<\/strong>\s*([^<]+)/);
        const agendaMatch = html.match(/Agenda:<\/strong>\s*([^<]+)/);

        const title = titleMatch?.[1]?.trim() || "Meeting";
        const dateStr = dateMatch?.[1]?.trim() || "";
        const durationMatch = dateStr.match(/\(Duration:\s*(\d+\s*minutes)\)/);

        return {
            title,
            date: dateStr.replace(/\(Duration:.*\)/, "").trim(),
            duration: durationMatch?.[1] || "",
            attendees: attendeesMatch?.[1]?.split(",").map(a => a.trim()) || [],
            agenda: agendaMatch?.[1]?.trim() || "",
        };
    } catch {
        return null;
    }
};

// Helper: Parse action items from HTML
const parseActionItems = (html: string): ActionItem[] => {
    const items: ActionItem[] = [];
    const regex = /<strong>Task:<\/strong>\s*([^<]+)<br>Owner:\s*([^<]+)<br>Deadline:\s*([^<]+)/g;
    let match;
    
    while ((match = regex.exec(html)) !== null) {
        items.push({
            task: match[1].trim(),
            owner: match[2].trim(),
            deadline: match[3].trim(),
        });
    }
    
    return items;
};

/**
 * MeetingNotesGenerator Component
 * 
 * Displays meeting notes generated by the agentflow:
 * - Summary from Meeting Summarizer
 * - MOM from Meeting MoM Generator  
 * - Action Items from Meeting Action Items Generator
 * - Email sending status
 */
const MeetingNotesGenerator: React.FC<ExecutionComponentProps> = ({
    logs,
    isLoading,
    isFetching,
}) => {
    const [activeTab, setActiveTab] = useState<"summary" | "mom" | "actions">("summary");

    // Parse the execution logs to extract meeting data
    const parsedData = useMemo<ParsedMeetingData>(() => {
        const result: ParsedMeetingData = {
            meetingDetails: null,
            summary: "",
            summaryHtml: "",
            mom: "",
            momHtml: "",
            actionItems: [],
            actionItemsHtml: "",
            emailSent: false,
            emailId: "",
            trackingId: "",
        };

        if (!logs?.execution_context) return result;

        const executionContext = logs.execution_context;

        // Loop through all agents in execution_context
        Object.values(executionContext).forEach((agentData: any) => {
            const agentRole = agentData?.agent_role || "";
            const outputData = agentData?.output_data;

            if (!outputData) return;

            // Meeting Summarizer
            if (agentRole === "Meeting Summarizer" && outputData?.content?.Meeting_Summary) {
                result.summaryHtml = outputData.content.Meeting_Summary;
                result.summary = stripHtml(outputData.content.Meeting_Summary);
            }

            // Meeting MoM Generator
            if (agentRole === "Meeting MoM Generator" && outputData?.content?.Meeting_MOM) {
                result.momHtml = outputData.content.Meeting_MOM;
                result.mom = stripHtml(outputData.content.Meeting_MOM);

                // Extract meeting details from MOM HTML
                result.meetingDetails = extractMeetingDetails(outputData.content.Meeting_MOM);
            }

            // Meeting Action Items Generator
            if (agentRole === "Meeting Action Items Generator" && outputData?.content?.Meeting_Action_Points) {
                result.actionItemsHtml = outputData.content.Meeting_Action_Points;
                result.actionItems = parseActionItems(outputData.content.Meeting_Action_Points);
            }

            // Email Sender
            if (agentRole === "Email Sender" && outputData?.mail_sent_data) {
                result.emailSent = true;
                result.trackingId = outputData.mail_sent_data.tracking_id || "";
            }
        });

        // Get email from input_variables (cast logs to any to access input_variables)
        const logsAny = logs as any;
        if (logsAny?.input_variables?.email_id) {
            result.emailId = logsAny.input_variables.email_id;
        }

        return result;
    }, [logs]);

    // Check if we're still processing
    const isProcessing = isLoading || isFetching || logs?.status === "running";
    const isCompleted = logs?.status === "completed";
    const hasError = logs?.status === "failed";

    // Loading State
    if (isProcessing && !parsedData.summaryHtml) {
        return (
            <div className="w-full flex justify-center">
                <div className="max-w-2xl w-full">
                    <div className="bg-[hsl(var(--surface-container-default))] rounded-3xl shadow-lg border border-[hsl(var(--stroke-soft))] overflow-hidden">
                        {/* Animated header bar */}
                        <div className="h-1.5 bg-gradient-to-r from-purple-500 via-indigo-500 to-purple-500 bg-[length:200%_100%] animate-[shimmer_2s_ease-in-out_infinite]" />
                        
                        <div className="px-8 py-10">
                            {/* Animated Icon */}
                            <div className="flex justify-center mb-8">
                                <div className="relative">
                                    <div className="absolute inset-0 rounded-full bg-purple-400/20 animate-ping" style={{ animationDuration: '2s' }} />
                                    <div className="absolute -inset-2 rounded-full border-2 border-purple-300/30 animate-pulse" />
                                    <div className="relative h-16 w-16 rounded-full bg-gradient-to-br from-purple-500 to-indigo-600 flex items-center justify-center shadow-lg">
                                        <Sparkles className="w-8 h-8 text-white" />
                                    </div>
                                </div>
                            </div>

                            <div className="text-center mb-8">
                                <h2 className="text-lg font-semibold text-[hsl(var(--text-inverse-default))] mb-2">
                                    Generating Meeting Notes
                                </h2>
                                <p className="text-sm text-[hsl(var(--text-inverse-subtle))]">
                                    AI is analyzing transcript and creating summary, MOM & action items
                                </p>
                            </div>

                            {/* Animated dots loader */}
                            <div className="flex justify-center gap-1.5 mb-8">
                                <div className="w-2 h-2 rounded-full bg-purple-500 animate-bounce" style={{ animationDelay: '0ms' }} />
                                <div className="w-2 h-2 rounded-full bg-purple-500 animate-bounce" style={{ animationDelay: '150ms' }} />
                                <div className="w-2 h-2 rounded-full bg-purple-500 animate-bounce" style={{ animationDelay: '300ms' }} />
                            </div>

                            {/* Progress indicators */}
                            <div className="flex justify-center gap-6">
                                <div className="flex flex-col items-center gap-2">
                                    <div className="h-10 w-10 rounded-xl bg-purple-50 flex items-center justify-center">
                                        <FileText className="w-5 h-5 text-purple-600" />
                                    </div>
                                    <span className="text-xs text-[hsl(var(--text-inverse-subtlest))]">Summary</span>
                                </div>
                                <div className="flex flex-col items-center gap-2">
                                    <div className="h-10 w-10 rounded-xl bg-purple-50 flex items-center justify-center">
                                        <ClipboardList className="w-5 h-5 text-purple-600" />
                                    </div>
                                    <span className="text-xs text-[hsl(var(--text-inverse-subtlest))]">MOM</span>
                                </div>
                                <div className="flex flex-col items-center gap-2">
                                    <div className="h-10 w-10 rounded-xl bg-purple-50 flex items-center justify-center">
                                        <ListChecks className="w-5 h-5 text-purple-600" />
                                    </div>
                                    <span className="text-xs text-[hsl(var(--text-inverse-subtlest))]">Actions</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        );
    }

    // Error State
    if (hasError) {
        return (
            <div className="w-full flex justify-center">
                <div className="max-w-md w-full">
                    <div className="bg-[hsl(var(--surface-container-default))] rounded-3xl shadow-lg border border-[hsl(var(--stroke-soft))] overflow-hidden">
                        <div className="h-1.5 bg-gradient-to-r from-red-500 to-orange-500" />
                        <div className="px-8 py-10 text-center">
                            <div className="h-14 w-14 rounded-full bg-red-100 flex items-center justify-center mx-auto mb-4">
                                <AlertCircle className="w-7 h-7 text-red-600" />
                            </div>
                            <h2 className="text-lg font-semibold text-[hsl(var(--text-inverse-default))] mb-2">
                                Failed to Generate Notes
                            </h2>
                            <p className="text-sm text-[hsl(var(--text-inverse-subtle))]">
                                Something went wrong while processing the meeting. Please try again.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        );
    }

    // Main Success UI
    return (
        <div className="w-full flex justify-center">
            <div className="max-w-3xl w-full">
                <div className="bg-[hsl(var(--surface-container-default))] rounded-3xl shadow-lg border border-[hsl(var(--stroke-soft))] overflow-hidden">
                    {/* Header with gradient */}
                    <div className="bg-gradient-to-r from-[hsl(var(--brand-purple-600))] to-[hsl(var(--brand-purple-800))] px-6 py-5">
                        <div className="flex items-start justify-between">
                            <div className="flex items-center gap-3">
                                <div className="h-12 w-12 rounded-2xl bg-white/20 backdrop-blur-sm flex items-center justify-center">
                                    <Sparkles className="w-6 h-6 text-white" />
                                </div>
                                <div>
                                    <h2 className="text-lg font-bold text-white">
                                        {parsedData.meetingDetails?.title || "Meeting Notes"}
                                    </h2>
                                    <p className="text-purple-200 text-sm">
                                        AI-Generated Summary & Action Items
                                    </p>
                                </div>
                            </div>
                            {parsedData.emailSent && (
                                <div className="flex items-center gap-2 bg-white/20 rounded-full px-3 py-1.5">
                                    <CheckCircle2 className="w-4 h-4 text-green-300" />
                                    <span className="text-white text-xs font-medium">Email Sent</span>
                                </div>
                            )}
                        </div>

                        {/* Meeting metadata */}
                        {parsedData.meetingDetails && (
                            <div className="flex flex-wrap gap-3 mt-4">
                                {parsedData.meetingDetails.date && (
                                    <div className="flex items-center gap-1.5 bg-white/10 rounded-full px-3 py-1">
                                        <Calendar className="w-3.5 h-3.5 text-purple-200" />
                                        <span className="text-white text-xs">{parsedData.meetingDetails.date}</span>
                                    </div>
                                )}
                                {parsedData.meetingDetails.duration && (
                                    <div className="flex items-center gap-1.5 bg-white/10 rounded-full px-3 py-1">
                                        <Clock className="w-3.5 h-3.5 text-purple-200" />
                                        <span className="text-white text-xs">{parsedData.meetingDetails.duration}</span>
                                    </div>
                                )}
                                {parsedData.meetingDetails.attendees.length > 0 && (
                                    <div className="flex items-center gap-1.5 bg-white/10 rounded-full px-3 py-1">
                                        <Users className="w-3.5 h-3.5 text-purple-200" />
                                        <span className="text-white text-xs">{parsedData.meetingDetails.attendees.length} attendees</span>
                                    </div>
                                )}
                            </div>
                        )}
                    </div>

                    {/* Tab Navigation */}
                    <div className="border-b border-[hsl(var(--stroke-soft))]">
                        <div className="flex">
                            <button
                                type="button"
                                onClick={() => setActiveTab("summary")}
                                className={`flex-1 flex items-center justify-center gap-2 py-4 text-sm font-medium transition-all border-b-2 ${
                                    activeTab === "summary"
                                        ? "border-[hsl(var(--brand-purple-600))] text-[hsl(var(--brand-purple-600))] bg-[hsl(var(--brand-purple-100))]/30"
                                        : "border-transparent text-[hsl(var(--text-inverse-subtle))] hover:text-[hsl(var(--text-inverse-default))] hover:bg-[hsl(var(--surface-container-active))]"
                                }`}
                            >
                                <FileText className="w-4 h-4" />
                                Summary
                            </button>
                            <button
                                type="button"
                                onClick={() => setActiveTab("mom")}
                                className={`flex-1 flex items-center justify-center gap-2 py-4 text-sm font-medium transition-all border-b-2 ${
                                    activeTab === "mom"
                                        ? "border-[hsl(var(--brand-purple-600))] text-[hsl(var(--brand-purple-600))] bg-[hsl(var(--brand-purple-100))]/30"
                                        : "border-transparent text-[hsl(var(--text-inverse-subtle))] hover:text-[hsl(var(--text-inverse-default))] hover:bg-[hsl(var(--surface-container-active))]"
                                }`}
                            >
                                <ClipboardList className="w-4 h-4" />
                                Minutes
                            </button>
                            <button
                                type="button"
                                onClick={() => setActiveTab("actions")}
                                className={`flex-1 flex items-center justify-center gap-2 py-4 text-sm font-medium transition-all border-b-2 ${
                                    activeTab === "actions"
                                        ? "border-[hsl(var(--brand-purple-600))] text-[hsl(var(--brand-purple-600))] bg-[hsl(var(--brand-purple-100))]/30"
                                        : "border-transparent text-[hsl(var(--text-inverse-subtle))] hover:text-[hsl(var(--text-inverse-default))] hover:bg-[hsl(var(--surface-container-active))]"
                                }`}
                            >
                                <ListChecks className="w-4 h-4" />
                                Actions
                                {parsedData.actionItems.length > 0 && (
                                    <span className="ml-1 bg-[hsl(var(--brand-purple-600))] text-white text-[10px] font-bold px-1.5 py-0.5 rounded-full">
                                        {parsedData.actionItems.length}
                                    </span>
                                )}
                            </button>
                        </div>
                    </div>

                    {/* Tab Content */}
                    <div className="p-6">
                        {/* Summary Tab */}
                        {activeTab === "summary" && (
                            <div className="prose prose-sm max-w-none">
                                {parsedData.summaryHtml ? (
                                    <div 
                                        className="meeting-notes-content text-[hsl(var(--text-inverse-default))]"
                                        dangerouslySetInnerHTML={{ __html: parsedData.summaryHtml }}
                                    />
                                ) : (
                                    <div className="text-center py-8 text-[hsl(var(--text-inverse-subtle))]">
                                        <FileText className="w-8 h-8 mx-auto mb-2 opacity-50" />
                                        <p>No summary available</p>
                                    </div>
                                )}
                            </div>
                        )}

                        {/* MOM Tab */}
                        {activeTab === "mom" && (
                            <div className="prose prose-sm max-w-none">
                                {parsedData.momHtml ? (
                                    <div 
                                        className="meeting-notes-content text-[hsl(var(--text-inverse-default))]"
                                        dangerouslySetInnerHTML={{ __html: parsedData.momHtml }}
                                    />
                                ) : (
                                    <div className="text-center py-8 text-[hsl(var(--text-inverse-subtle))]">
                                        <ClipboardList className="w-8 h-8 mx-auto mb-2 opacity-50" />
                                        <p>No minutes available</p>
                                    </div>
                                )}
                            </div>
                        )}

                        {/* Action Items Tab */}
                        {activeTab === "actions" && (
                            <div>
                                {parsedData.actionItems.length > 0 ? (
                                    <div className="space-y-3">
                                        {parsedData.actionItems.map((item, index) => (
                                            <div 
                                                key={index}
                                                className="bg-[hsl(var(--surface-container-default-lighter))] rounded-xl p-4 border border-[hsl(var(--stroke-soft))] hover:border-[hsl(var(--brand-purple-300))] transition-colors"
                                            >
                                                <div className="flex items-start gap-3">
                                                    <div className="h-6 w-6 rounded-full bg-[hsl(var(--brand-purple-600))] flex items-center justify-center flex-shrink-0 mt-0.5">
                                                        <span className="text-white text-xs font-bold">{index + 1}</span>
                                                    </div>
                                                    <div className="flex-1 min-w-0">
                                                        <p className="text-sm font-medium text-[hsl(var(--text-inverse-default))] mb-2">
                                                            {item.task}
                                                        </p>
                                                        <div className="flex flex-wrap gap-2">
                                                            <div className="flex items-center gap-1.5 bg-[hsl(var(--surface-container-raised))] rounded-full px-2.5 py-1">
                                                                <User className="w-3 h-3 text-[hsl(var(--text-inverse-subtle))]" />
                                                                <span className="text-xs text-[hsl(var(--text-inverse-default))]">{item.owner}</span>
                                                            </div>
                                                            <div className="flex items-center gap-1.5 bg-[hsl(var(--accent-orange-300))]/20 rounded-full px-2.5 py-1">
                                                                <Calendar className="w-3 h-3 text-[hsl(var(--accent-orange-600))]" />
                                                                <span className="text-xs text-[hsl(var(--accent-orange-600))] font-medium">{item.deadline}</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                ) : (
                                    <div className="text-center py-8 text-[hsl(var(--text-inverse-subtle))]">
                                        <ListChecks className="w-8 h-8 mx-auto mb-2 opacity-50" />
                                        <p>No action items recorded</p>
                                    </div>
                                )}
                            </div>
                        )}
                    </div>

                    {/* Footer */}
                    <div className="px-6 py-4 border-t border-[hsl(var(--stroke-soft))] bg-[hsl(var(--surface-container-default-lighter))]">
                        <div className="flex items-center justify-between">
                            <div className="flex items-center gap-2">
                                {parsedData.emailSent || parsedData.emailId ? (
                                    <div className="flex items-center gap-2 text-[hsl(var(--accent-lime-600))]">
                                        <CheckCircle2 className="w-4 h-4" />
                                        <span className="text-sm font-medium">Sent to {parsedData.emailId}</span>
                                    </div>
                                ) : (
                                    <p className="text-xs text-[hsl(var(--text-inverse-subtlest))]">
                                        Powered by Wexa AI
                                    </p>
                                )}
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            {/* CSS for HTML content styling */}
            <style jsx global>{`
                .meeting-notes-content h3 {
                    font-size: 1.125rem;
                    font-weight: 600;
                    margin-bottom: 1rem;
                    color: hsl(var(--text-inverse-default));
                }
                .meeting-notes-content h4 {
                    font-size: 0.95rem;
                    font-weight: 600;
                    margin-top: 1.25rem;
                    margin-bottom: 0.5rem;
                    color: hsl(var(--brand-purple-600));
                }
                .meeting-notes-content h5 {
                    font-size: 0.875rem;
                    font-weight: 600;
                    margin-top: 1rem;
                    margin-bottom: 0.375rem;
                    color: hsl(var(--text-inverse-default));
                }
                .meeting-notes-content ul {
                    list-style-type: disc;
                    padding-left: 1.5rem;
                    margin-bottom: 1rem;
                }
                .meeting-notes-content li {
                    margin-bottom: 0.5rem;
                    color: hsl(var(--text-inverse-default));
                    line-height: 1.6;
                }
                .meeting-notes-content strong {
                    font-weight: 600;
                    color: hsl(var(--text-inverse-default));
                }
                .meeting-notes-content p {
                    margin-bottom: 0.75rem;
                    line-height: 1.6;
                }
            `}</style>
        </div>
    );
};

export default MeetingNotesGenerator;

